### ISSUE TITLE
Write a good README

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/university#5]
Not sure exactly what the README should contain yet. Definitely an overview of the purpose of this repo (to help facilitate the expansion of YACS to other universities). It should be clear that this is an organizational repo, not a code repo. Maybe...

- Goals for expanding YACS
- How you can get involved
- What types of issues belong here vs. the code repositories
- How you can facilitate bringing YACS to your school

Any suggestions?

**Comment by kburk1997** [comment]
I’d suggest adding something about the YACS Code of Conduct and allow for non-RCOS-specific changes (especially since other universities may handle stuff differently than RPI and should an incident occur at another school a solid response plan should be outlined)

**Comment by kburk1997** [comment]
Also: there are some inconsistencies with regards to the Code of Conduct used across the YACS project. 

YACS repositories using modified Contributor Covenant CoC:
- [yacs](https://github.com/YACS-RCOS/yacs)
- [yacs-web](https://github.com/YACS-RCOS/yacs-web)
- [yacs-auth](https://github.com/YACS-RCOS/yacs-auth)

YACS repositories using modified RCOS Community CoC:
- [yacs-admin](https://github.com/YACS-RCOS/yacs-admin)

YACS repositories with no Code of Conduct (:cry:):
- [yacs-rcos.github.io](https://github.com/YACS-RCOS/yacs-rcos.github.io) - this should probably be taken care of to prevent people from making inflammatory blog posts
- [yacs-orchestra](https://github.com/YACS-RCOS/yacs-orchestra)
- [yacs-prereq-data](https://github.com/YACS-RCOS/yacs-prereq-data)
- [yacs-prereq-web](https://github.com/YACS-RCOS/yacs-prereq-web)
- [yacs-malg](https://github.com/YACS-RCOS/yacs-malg)
- [yacs-BI](https://github.com/YACS-RCOS/yacs-BI)
- [yacs-nginx](https://github.com/YACS-RCOS/yacs-nginx)
- [yacs-public](https://github.com/YACS-RCOS/yacs-public)
- [yacs-users](https://github.com/YACS-RCOS/yacs-users)

Not included on the list: some stale repos

Ideally, we should have a universal YACS Code of Conduct as soon as possible, and get input from BUGS @ NYU since they may choose to handle violations of the Code of Conduct differently than we do

**Comment by Bad-Science** [comment]
@kburk1997 Good point, we should pick a consistent version and make sure it is in all of the repos

**Comment by Bad-Science** [comment]
We are deprecating this repository in favor of a mono-repo. This documentation should exist in docs. Closing this.
